---Creacion de tabla fuerte
CREATE TABLE DEPARTAMENTOS(
DEPTNO NUMBER PRIMARY KEY NOT NULL,
D_NAME VARCHAR2(80),
LOC VARCHAR2(80)
);

INSERT INTO DEPARTAMENTOS VALUES(10,'CONTABILIDAD','NEW YORK');
INSERT INTO DEPARTAMENTOS VALUES(20,'INVESTIGACION','DALLAS');
INSERT INTO DEPARTAMENTOS VALUES(30,'VENTAS','CHICAGO');
INSERT INTO DEPARTAMENTOS VALUES(40,'OPERACION','BOSTON');
COMMIT;
SELECT * FROM DEPARTAMENTOS;
--TABLA DEBIL 
CREATE TABLE EMPLEADO(
EMPNO NUMBER PRIMARY KEY NOT NULL,
ENAME VARCHAR2(80) NOT NULL,
PUESTO VARCHAR2(80) NOT NULL,
DEPTO NUMBER NOT NULL,
SAL NUMBER NOT NULL,
COMM NUMBER,
MGR NUMBER,
FOREIGN KEY(DEPTO) REFERENCES DEPARTAMENTOS(DEPTNO)
);

INSERT INTO EMPLEADO VALUES (7839, 'Juan', 'vendedor', 30, 2850, NULL, 7566);
INSERT INTO EMPLEADO VALUES (7698, 'Maria', 'senior', 30, 2450, NULL, 7566);
INSERT INTO EMPLEADO VALUES (7782, 'Jose', 'senior', 30, 2975, NULL, 7566);
INSERT INTO EMPLEADO VALUES (7566, 'Miguel', 'Presidente', 30, 11250, NULL, NULL);
INSERT INTO EMPLEADO VALUES (7654, 'Sebastián', 'Analista', 20, 3000, 1400, 7566);
INSERT INTO EMPLEADO VALUES (7499, 'Emilio', 'Analista', 20, 3000, 300, 7698);
INSERT INTO EMPLEADO  VALUES (7844, 'Roberta', 'Analista', 20, 3000, NULL, 7782);
INSERT INTO EMPLEADO  VALUES (7900, 'Arnold', 'Mostrador', 30, 1500, NULL, 7782);
INSERT INTO EMPLEADO VALUES (7521, 'Miriam', 'Mostrador', 30, 1500, 500, 7698);
INSERT INTO EMPLEADO  VALUES (7902, 'Marco', 'Mostrador', 30, 1500, NULL, 7782);
INSERT INTO EMPLEADO  VALUES (7369, 'Pedro', 'Analista', 20, 3000, NULL, 7698);
INSERT INTO EMPLEADO  VALUES (7788, 'Sofía', 'Analista', 20, 3000, NULL, 7698);
INSERT INTO EMPLEADO  VALUES (7876, 'Alejandra', 'vendedor', 30, 1600, NULL, 7782);
INSERT INTO EMPLEADO VALUES (7934, 'Ana María', 'vendedor', 30, 1300, NULL, 7566);
SELECT * FROM EMPLEADO;

SELECT ENAME,PUESTO,SAL salary FROM EMPLEADO;

SELECT empno ,ename ,sal * 12 AnnualSalary From EMPLEADO;

SELECT EMPNO,DEPTO FROM EMPLEADO WHERE EMPNO=7654; 

SELECT E.EMPNO AS NOMBRE,D.D_NAME AS DEPATAMENTO,E.SAL AS SALARIO,E.COMM AS COMISION FROM DEPARTAMENTOS D 
INNER JOIN EMPLEADO E ON D.DEPTNO = E.DEPTO ; 

Select   e.ename 
,e.hiredate
,m.ename
,m.hiredate 
	From emp e
        ,emp m
	Where e.mgr=m.empno
                 And e.hiredate<m.hiredate;
                 
CREATE VIEW CONTAR AS
SELECT DEPTNO CANTIDAD_DEPARTAMENTOFROM FROM DEPARTAMENTOS WHERE DEPTNO = (SELECT COUNT(*) FROM DEPARTAMENTOS);
SELECT COUNT(*) FROM DEPARTAMENTOS;
SELECT * FROM CONTAR;

















