----Tablas fuertes
CREATE TABLE GENERO(
    ID_GENERO NUMBER PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR2(20) NOT NULL
);

INSERT INTO GENERO VALUES(1,'FEMENINO');
INSERT INTO GENERO VALUES(2,'MASCULINO');
COMMIT;

SELECT * FROM GENERO;

CREATE TABLE TRABAJOS(
    ID_TRABAJO NUMBER PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR2(255)NOT NULL,
    SALARIO NUMBER(9,2)NOT NULL
);

INSERT INTO TRABAJOS VALUES(1,'DESARROLLADO',18000.23);
INSERT INTO TRABAJOS VALUES(2,'MANTENIMIENTO',16000.01);
COMMIT;

SELECT * FROM TRABAJOS;

---TABLAS DEBILES 

CREATE TABLE EMPLEADOS_(
    ID_EMPLEADO NUMBER PRIMARY KEY NOT NULL,
    FK_GENERO NUMBER NOT NULL,
    FK_TRABAJO NUMBER NOT NULL,
    NOMBRE VARCHAR2(255)NOT NULL,
    APELLIDO_PATERNO VARCHAR2(255)NOT NULL,
    FECHA_NACIMINETO DATE NOT NULL,
    FOREIGN KEY(FK_GENERO) REFERENCES GENERO(ID_GENERO),
    FOREIGN KEY(FK_TRABAJO) REFERENCES TRABAJOS(ID_TRABAJO)
);

INSERT INTO EMPLEADOS_ VALUES(1,2,1,'JOSE','ESTRADA','25/08/2008');
INSERT INTO EMPLEADOS_ VALUES(2,1,2,'ANDREA','MONTIEL','25/08/2007');
COMMIT;
SELECT * FROM empleados_;

CREATE TABLE EMPLEADO_HORAS_TRABAJADAS(
    ID_EMPLEADO_HORAS_TRABAJADAS NUMBER PRIMARY KEY NOT NULL,
    FK_EMPLEADO NUMBER NOT NULL,
    HORAS_TRABAJADAS NUMBER NOT NULL,
    FECHA_TRABAJO DATE NOT NULL,
    FOREIGN KEY(FK_EMPLEADO) REFERENCES EMPLEADOS_(ID_EMPLEADO) 
);

INSERT INTO EMPLEADO_HORAS_TRABAJADAS VALUES(1,2,89,'04/04/2025');
INSERT INTO EMPLEADO_HORAS_TRABAJADAS VALUES(2,1,100,'04/04/2025');
COMMIT;
SELECT * FROM EMPLEADO_HORAS_TRABAJADAS;











