----TABLAS FUERTES 
CREATE TABLE PACIENTE(
ID_PACIENTE NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(30)NOT NULL,
APELLIDOS VARCHAR(40)NOT NULL,
EDAD INT NOT NULL
);

CREATE TABLE DOCTOR(
ID_DOCTOR NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(80) NOT NULL,
ESPECIALIDAD VARCHAR2(80) NOT NULL
);

----TABLAS DEBILES 
CREATE TABLE CITAS(
ID_CITA NUMBER PRIMARY KEY,
FECHA DATE NOT NULL,
FK_PACIENTE NUMBER NOT NULL,
HORA_INICIO DATE NOT NULL,
HORA_FIN DATE NOT NULL,
FK_DOCTOR NUMBER NOT NULL,
FOREIGN KEY(FK_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE),
FOREIGN KEY(FK_DOCTOR) REFERENCES DOCTOR(ID_DOCTOR)
);

CREATE TABLE CONSULTORIO(
ID_CONSULTORIO NUMBER PRIMARY KEY,
PISO INT NOT NULL,
AREA VARCHAR2(80),
FK_DOCTOR NUMBER NOT NULL,
FOREIGN KEY(FK_DOCTOR) REFERENCES DOCTOR(ID_DOCTOR)
);
-----CREADNDO LOS AUTO INCREMENTABLES 
CREATE SEQUENCE SECUENCIA_ID_PACIENTE
START WITH 1
INCREMENT BY 1;

DROP SEQUENCE SECUENCIA_ID_DOCTOR;

CREATE SEQUENCE SECUENCIA_ID_DOCTOR
START WITH 1 
INCREMENT BY 1;

CREATE SEQUENCE SECUNCIA_ID_CITA
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SECUENCIA_ID_CONSULTORIO
START WITH 1
INCREMENT BY 1;

----CREANDO LOS TRIGGERS O DISPARADORES PARA EJECUTAR EL AUTO  INCREMENTO
CREATE OR REPLACE TRIGGER EJECUTAR_SECUENCIA_PACIENTE
BEFORE INSERT 
ON PACIENTE 
FOR EACH ROW 
BEGIN 
    SELECT SECUENCIA_ID_PACIENTE.NEXTVAL INTO:NEW.ID_PACIENTE FROM DUAL;
END;

CREATE OR REPLACE TRIGGER EJECUTAR_SECUENCIA_DOCTOR
BEFORE INSERT
ON DOCTOR
FOR EACH ROW
BEGIN 
    SELECT SECUENCIA_ID_DOCTOR.NEXTVAL INTO:NEW.ID_DOCTOR FROM DUAL;
END;

CREATE OR REPLACE TRIGGER EJECUTAR_SECUENCIA_CITAS
BEFORE INSERT
ON CITAS
FOR EACH ROW
BEGIN 
    SELECT SECUNCIA_ID_CITA.NEXTVAL INTO:NEW.ID_CITA FROM DUAL;
END;

CREATE OR REPLACE TRIGGER EJECUTAR_SECUENCIA_COOSULTORIO
BEFORE INSERT
ON CONSULTORIO 
FOR EACH ROW
BEGIN
    SELECT SECUENCIA_ID_CONSULTORIO.NEXTVAL INTO:NEW.ID_CONSULTORIO FROM DUAL;
END;

----CREANDO PROCEDIMIENTOS ALMACENADOS PARA GUARDAR DATOS EN LAS TABLAS PACIENTES
CREATE OR REPLACE PROCEDURE AGREGAR_NUEVO_PACIENTE
(AGREGAR_NOMBRE PACIENTE.NOMBRE%TYPE,
AGREGAR_APELLIDOS PACIENTE.APELLIDOS%TYPE,AGREGAR_EDAD NUMBER)
AS BEGIN
    INSERT INTO PACIENTE(NOMBRE,APELLIDOS,EDAD)VALUES(AGREGAR_NOMBRE,AGREGAR_APELLIDOS,AGREGAR_EDAD);
    COMMIT;
END;

EXECUTE AGREGAR_NUEVO_PACIENTE('JOSE','TORRES',45);
EXECUTE AGREGAR_NUEVO_PACIENTE('JUAN', 'PEREZ', 30);
EXECUTE AGREGAR_NUEVO_PACIENTE('MARIA', 'LOPEZ', 25);
EXECUTE AGREGAR_NUEVO_PACIENTE('CARLOS', 'GARCIA', 40);
EXECUTE AGREGAR_NUEVO_PACIENTE('ANA', 'RODRIGUEZ', 35);
EXECUTE AGREGAR_NUEVO_PACIENTE('LUIS', 'HERNANDEZ', 50);
EXECUTE AGREGAR_NUEVO_PACIENTE('SOFIA', 'MARTINEZ', 28);
EXECUTE AGREGAR_NUEVO_PACIENTE('PEDRO', 'GOMEZ', 45);
EXECUTE AGREGAR_NUEVO_PACIENTE('ELENA', 'DIAZ', 33);
EXECUTE AGREGAR_NUEVO_PACIENTE('MIGUEL', 'FERNANDEZ', 60);
EXECUTE AGREGAR_NUEVO_PACIENTE('LAURA', 'TORO', 22);


---CREANDO PROCEDIMIENTOO ALMACENADO PARA AGREGAR NUEVOS DOCTORES
CREATE OR REPLACE PROCEDURE AGREGAR_NUEVO_DOCTOR
(AGREGAR_NOMBRE DOCTOR.NOMBRE%TYPE,
AGREGAR_ESPECIALIDAD DOCTOR.ESPECIALIDAD%TYPE)
AS BEGIN
    INSERT INTO DOCTOR(NOMBRE,ESPECIALIDAD)VALUES(AGREGAR_NOMBRE,AGREGAR_ESPECIALIDAD);
    COMMIT;
END;

EXECUTE AGREGAR_NUEVO_DOCTOR('RAUL', 'CARDIOLOGO');
EXECUTE AGREGAR_NUEVO_DOCTOR('MARINA', 'PEDIATRA');
EXECUTE AGREGAR_NUEVO_DOCTOR('JORGE', 'DERMATOLOGO');
EXECUTE AGREGAR_NUEVO_DOCTOR('ANA', 'NEUROLOGA');
EXECUTE AGREGAR_NUEVO_DOCTOR('LUIS', 'ORTOPEDISTA');

---CREANDO PROCEDIMIENTO ALMACENADO PARA CONSULTORIO
CREATE OR REPLACE PROCEDURE AGREGAR_NUEVO_CONSULTORIO
(AGREGAR_PISO CONSULTORIO.PISO%TYPE,
AGREGAR_AREA CONSULTORIO.AREA%TYPE,AGREGAR_DOCTOR CONSULTORIO.FK_DOCTOR%TYPE)
AS BEGIN
    INSERT INTO CONSULTORIO(PISO,AREA,FK_DOCTOR)VALUES(AGREGAR_PISO,AGREGAR_AREA,AGREGAR_DOCTOR);
    COMMIT;
END;

EXECUTE AGREGAR_NUEVO_CONSULTORIO(1, 'CARDIOLOGÍA', 1);
EXECUTE AGREGAR_NUEVO_CONSULTORIO(2, 'PEDIATRÍA', 2);
EXECUTE AGREGAR_NUEVO_CONSULTORIO(3, 'DERMATOLOGÍA', 3);
EXECUTE AGREGAR_NUEVO_CONSULTORIO(4, 'NEUROLOGÍA', 4);
EXECUTE AGREGAR_NUEVO_CONSULTORIO(5, 'ORTOPEDIA', 5);
EXECUTE AGREGAR_NUEVO_CONSULTORIO(1, 'CARDIOLOGÍA', 1);
EXECUTE AGREGAR_NUEVO_CONSULTORIO(2, 'PEDIATRÍA', 2);
EXECUTE AGREGAR_NUEVO_CONSULTORIO(3, 'DERMATOLOGÍA', 3);

---CREANDO PROCEDIMIENTO ALMACENADO PARA CITAS
CREATE OR REPLACE PROCEDURE AGREGAR_NUEVA_CITA
(AGREGAR_FECHA CITAS.FECHA%TYPE,AGREGAR_PACIENTE CITAS.FK_PACIENTE%TYPE,
AGREGAR_INICIO CITAS.HORA_INICIO%TYPE,AGREGAR_FIN CITAS.HORA_FIN%TYPE,
AGREGAR_DOCTOR CITAS.FK_DOCTOR)
AS BEGIN
    INSERT INTO CITAS(FECHA,FK_PACIENTE,HORA_INICIO,HORA_FIN,FK_DOCTOR)
    VALUES(AGREGAR_FECHA,AGREGAR_PACIENTE,AGREGAR_INICO,AGREGAR_FIN,AGREGAR_DOCTOR);
    COMMIT;
END;


SELECT * FROM PACIENTE;
SELECT * FROM DOCTOR;





























