CREATE TABLE OCUPACION(
    ACTIVIDAD NUMBER PRIMARY KEY,
    DESCRIPCION VARCHAR2(80)NOT NULL,
    SUELDO INT NOT NULL
);

CREATE TABLE TABLA_EMPLEADO(
    ID_EMPLEADO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(80) NOT NULL,
    APELL_PATERNO VARCHAR2(80)NOT NULL,
    APELL_MATERNO VARCHAR2(80)NOT NULL,
    EDAD NUMBER NOT NULL,
    FK_ACTIVIDAD NUMBER NOT NULL,
    FOREIGN KEY(FK_ACTIVIDAD) REFERENCES OCUPACION(ACTIVIDAD)
);
INSERT INTO OCUPACION VALUES (1,'PANADERO',10);
INSERT INTO OCUPACION VALUES (2,'POLICIA',10);
INSERT INTO OCUPACION VALUES (3,'REPARTIDOR',5);
INSERT INTO OCUPACION VALUES (4,'GERENTE',15);
INSERT INTO OCUPACION VALUES (5,'SUPERVISOR',12);

INSERT INTO TABLA_EMPLEADO VALUES(1,'RUBEN','CARDENAS','PEREZ',35,1);
INSERT INTO TABLA_EMPLEADO VALUES(2,'JOSE','HUERTA','PEREZ',35,1);
INSERT INTO TABLA_EMPLEADO VALUES(3,'DAVID','HERNANDEZ','SUAREZ',31,3);
INSERT INTO TABLA_EMPLEADO VALUES(4,'GUSTAVO','RODRIGEZ','CHAVEZ',35,4);
INSERT INTO TABLA_EMPLEADO VALUES(5,'RICARDO','MONTES','JUAREZ',36,4);

SELECT NOMBRE,APELL_PATERNO,APELL_MATERNO FROM TABLA_EMPLEADO WHERE EDAD > 35;

SELECT TT.APELL_PATERNO,TT.NOMBRE,P.DESCRIPCION FROM TABLA_EMPLEADO TT INNER JOIN OCUPACION P ON TT.FK_ACTIVIDAD = P.ACTIVIDAD;

SELECT TT.NOMBRE,TT.EDAD 
FROM TABLA_EMPLEADO TT INNER JOIN OCUPACION P ON TT.FK_ACTIVIDAD = P.ACTIVIDAD
WHERE P.DESCRIPCION = 'REPARTIDOR';












